### ISSUE TITLE
[BUG] failed to resolve clamav-api

### ISSUE THREAD

**Issue by killmasta93** [bunkerity/bunkerweb-plugins#13]
**Plugin(s)**
CLAMAV

**Description**
ACCESS] clamav:access() call failed : error from request : error while sending request : clamav-api could not be resolved (2: Server failure), ` 

**How to reproduce**
copying the dockercompose example

**BunkerWeb version**
1.5

**Logs**
ACCESS] clamav:access() call failed : error from request : error while sending request : clamav-api could not be resolved (2: Server failure), ` 

i had to add the network to the docker compose for it to work

```
  clamav-api:
    image: bunkerity/bunkerweb-clamav
    environment:
      - CLAMAV_HOST=clamav
      - REDIS_HOST=redis
    networks:
      - bw-universe
      - bw-docker

  clamav:
    image: clamav/clamav:1.1.0
    volumes:
      - ./clamav-data:/var/lib/clamav
    networks:
      - bw-universe
      - bw-docker

  redis:
    image: redis:7-alpine
    networks:
      - bw-universe
      - bw-docker
```
