### ISSUE TITLE
[FEATURE] Crowdsec Dashboard

### ISSUE THREAD

**Issue by killmasta93** [bunkerity/bunkerweb-plugins#14]
**Plugin(s)**
Crowdsec
**What's needed and why ?**
Data info of crowdsec metrics

**Implementations ideas (optional)**
Im attaching the docker compose of the crowdsec which is working at the moment 

![image](https://github.com/bunkerity/bunkerweb-plugins/assets/13953629/7d2aa550-4274-4021-bd9f-03684b4c4aeb)

`wget https://raw.githubusercontent.com/crowdsecurity/example-docker-compose/main/crowdsec/dashboard/Dockerfile`

```
  crowdsec:
    image: crowdsecurity/crowdsec:v1.5.1
    volumes:
      - cs-data:/var/lib/crowdsec/data:rw
      - ./acquis.yaml:/etc/crowdsec/acquis.yaml
      - bw-logs:/var/log:ro
      - cs-config:/etc/crowdsec:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - BOUNCER_KEY_bunkerweb=s3cr3tb0unc3rk3y
      - COLLECTIONS=crowdsecurity/nginx
      - GID=1000
      - ENABLE_PARSERS=crowdsecurity/whitelists
    networks:
      - bw-universe

  dashboard:
    container_name: crowdsecdashboard
    build: ./dashboard
    restart: unless-stopped
    depends_on:
      - crowdsec
    networks:
      - bw-universe
    ports:
      - 1111:3000
    environment:
      - MB_DB_FILE=/data/metabase.db
      - MGID=1000
    volumes:
      - cs-data:/metabase-data/

volumes:
  bw-data:
   driver: local-persist
   driver_opts:
     mountpoint: /waf/sites/bw-data
  bw-logs:
   driver: local-persist
   driver_opts:
     mountpoint: /waf/sites/bw-logs
  cs-data:
   driver: local-persist
   driver_opts:
     mountpoint: /waf/sites/cs-data
  cs-config:
   driver: local-persist
   driver_opts:
     mountpoint: /waf/sites/cs-config

```
